### ISSUE TITLE
Pass other fields directly into the connection result

### ISSUE THREAD

**Issue by MatteoGranziera** [treedomtrees/paginated-connection#21]
Basically I need to pass `facets` field into the connection result on the same level of `edges` field.

```javascript
{
  facets: {} // I need to include this field in the connection that comes out of the dataloader function
  edges:[ {} ],
  totalCount: x
  pageInfo: { ... }
}
```

**Comment by MatteoGranziera** [comment]
Since would be a lot of catches and passing all other fields resulting from the dataloader cloud brake the standard adopted, It's better to handle this cases separately by spreading the paginatedConnection function result and add the other fields.

@DavideArena

**Comment by DavideArena** [comment]
@MatteoGranziera as you described in the last comment, passing more data inside the dataloader resulting field could be complex and out of adopted standard.
In the future, we could adapt the typing in order to prove a way to "extend" the expected type resolved by dataloder function, in order to add custom values.
Atm the solution to spread paginatedConnection function result and add the other fields is the best way.
Going to close the issue.
